# Generated by Django 5.0.4 on 2024-04-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoVault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
