# Generated by Django 5.0.4 on 2024-04-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoVault', '0002_alter_car_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
