# Generated by Django 5.0.4 on 2024-04-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoVault', '0003_car_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='total_price',
        ),
    ]
